### ISSUE TITLE
Missing and removed elements

### ISSUE THREAD

**Issue by j9t** [w3c/elements-of-html#18]
Updating the original index [1] and cross-checking the index here I noticed a few inaccuracies:

* <dialog> is part of HTML, but not of HTML 5.1
* <hgroup> is part of HTML, but not of HTML 5.1
* <rb> is not part of HTML
* <rtc> is not part of HTML

I’m feeling free to just report these for now.

[1] http://meiert.com/en/indices/html-elements/

**Comment by stevefaulkner** [comment]
thanks
