### ISSUE TITLE
Need for this index?

### ISSUE THREAD

**Issue by j9t** [w3c/elements-of-html#19]
Given that the original index at http://meiert.com/en/indices/html-elements/ seems more frequently updated and now also includes HTML 5.1 I wonder, is this index here still needed—or what plans are there for it?

In the beginning it seemed the version here would add value (HTML 5.1, community), but now it seems the original might just do (I have no plans to not update it in the future, either). I’m open to discussing ideas here so that we can make sure we a) add value to other developers and b) use our time effectively :)

**Comment by stevefaulkner** [comment]
hi Jens, I will keep going with this while HTML continues to be published at W3C, I have just updated it to 5.2 and fixed a bunch of links.
